### ISSUE TITLE
Hashcat bruteforce

### ISSUE THREAD

**Issue by tcinbis** [tcinbis/WPA2Cracking#2]
- [ ] describe example hashcat comand for bruteforce attack

 - [ ] what are charsets and how to use it?

 - [x] graph time to crack different passwords with bruteforce

 - [ ] distributed cracking with hashtopolis

 - [ ] example time to crack a handshake with 4 PC's

- [x] CPU script for performance test

- [x]  GPU script for performance test

- [x] CPU vs GPU difference

**Comment by MaxBurgert** [comment]
Report: https://de.sharelatex.com/4551811569tyrrbwbnbdmg
